### ISSUE TITLE
Posting Bug

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#1]
![sc2-sdk error](https://user-images.githubusercontent.com/15100667/36677005-00cd8412-1b05-11e8-8204-d3b2fe887f9a.png)

When posting, it does not process and gives `sc-sdk error` error msg.

**Comment by sydneyitguy** [comment]
@cyh76507707 
I don't see this problem anymore. Can  you check again?

**Comment by cyh76507707** [comment]
Solved
