### ISSUE TITLE
Clicking user profile pic

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#10]
![screenshot 2018-02-26 15 41 37](https://user-images.githubusercontent.com/15100667/36679623-91b03c4e-1b0b-11e8-9b33-c729e274d550.png)

When clicking the profile pic on the user profile page, it may be better to transfer to the user's Steemit page.

**Comment by sydneyitguy** [comment]
That would not be a intuitive solution I guess..

![image](https://user-images.githubusercontent.com/1332279/36884409-415e9c42-1e24-11e8-9284-8a94eb437a97.png)

How about this on the bottom of the page instead?

**Comment by cyh76507707** [comment]
Sure great.
