### ISSUE TITLE
Blank on Windows Explore

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#11]
When I'm launching Steemhunt website on Explore, Steemhunt website is suddenly changed to be blank after showing the main page for less than a second.

- Explore 11 (Parallels for Mac) 

![window-loading](https://user-images.githubusercontent.com/15100667/36680398-97f7ddbc-1b0d-11e8-882f-d22a56c1c040.png)

<img width="1422" alt="screenshot 2018-02-26 15 53 46" src="https://user-images.githubusercontent.com/15100667/36680411-9e886066-1b0d-11e8-9052-28c6bda713f2.png">

**Comment by sydneyitguy** [comment]
Maybe related to #17 17

**Comment by sydneyitguy** [comment]
![image](https://user-images.githubusercontent.com/1332279/36846636-c24ac294-1d9e-11e8-808f-390cee2e764e.png)

This is the coolest bug fix I've done in my life.. lol
