### ISSUE TITLE
No edit button

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#131]
Reported on Telegram

**Comment by tobias-g1** [comment]
I get this on too on the following environment:

Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
Device: MacBook Pro (Retina, 15-inch, Late 2013)
Operating system: MacOS HighSierra Version 10.13

Seems to show on Firefox though.

**Comment by astrocket** [comment]
Fixed.
https://github.com/Steemhunt/web/pull/251/commits/3e6df5e0dc8be7dade7279916eb90ef11969615f
