### ISSUE TITLE
Account Based Votings

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#135]
I guess we'll probably have to implement some kind of "Account based voting" before even SMT launched for a better quality of curations.

Steemhunt is based on Steem, so it inherits all the characteristics from Steem. On of them is:
- Payouts are dependent on account, not the  quality of the post
and that characteristic is probably okay if it's a blog, but it's not fair on Steemhunt like ranking board.

Backend changes - https://github.com/Steemhunt/api/issues/32

**Comment by sydneyitguy** [comment]
Only consider Steemhunt user's votings
> Only count hunter's voting - who has hunted at least 3 products

HUNT Score considers
1. VP: 1 - 100% => 1 - 10 points
2. Reputation: 
- 25 - 30 => x0.5
- 31 - 50 => x1
- 51 - 60 => x1.5 
- 61 - => x2.5

**Comment by cyh76507707** [comment]
`ABV - Beta`

[Purpose]
The new ranking algorithm is to make Steemhunt's ranking more based on Hunter's upvoting, not influenced by other Steem users or bid bots. However, complicated logics like Facebook will not be acceptable because it may reduce transparency. 
We'd like to try the very basic level of ABV first, and will see how it works first.

[Logic]
- One upvote has 10 points with 100% vp.
- The point proportionally decrease based on the hunter's set vp. For example, the hunter upvotes with 50% vp, the score will be 5 point.
- Whitelist: Scores are only be counted by the user who have hunted AT LEAST ONE TIME.

[Possible Progress]
We are thinking about several ways to develop this algorithms. These are JUST EXAMPLES we can think more later.
1) More intensive whitelist: counted by the hunters with at least three times, exclude blacklist hunters, etc.
2) Hunter's badge system: We can level the hunters based on their hunting history, from Lv.1 to Lv.5. 
- Lv.1: 1 hunts (1 full voting score: 10 poinst)
- Lv.2: 10 days hunting + 10 times upvoting the hunting posts (1 full voting score: 20 poinst)
- Lv.3: Lv.2 + at least 3 times on top 10 hunts (1 full voting score: 30 poinst)
- Lv.4: Lv.2 + at least 5 times on top 10 hunts (1 full voting score: 50 poinst)
- Lv.5: 30 days hunting + 30 times upvoting the hunting posts + at least 10 times on top 10 hunts. (1 full voting score: 100 poinst)
- The Lv can be downgraded if the hunter does not have any hunting or voting activities more than 10 days. (Lv 5 -> Lv 4 -> ...)

**Comment by zionopia** [comment]
If there is a leveling down system implemented, there has to be a rule how a leveled down account can get leveled up again. Suggestion would be like followed.

* Count only activities from the point of the date the level has been leveled down. System needs to be able to check the timing when the account has been leveled down an ignore all activities before that date.

* Example : Lv.5 leveled down to Lv. 3
                -> Starting new activity after 20 days, this account would need to get at least 5 times in the top 10 to get a Lv. 4.

**Comment by Chuuuckie** [comment]
More intensive whitelist: counted by the hunters with at least three times, exclude blacklist hunters, etc.
Hunter's badge system: We can level the hunters based on their hunting history, from Lv.1 to Lv.5.
- Lv.1: 1 hunts (1 full voting score: 10 poinst)
- Lv.2: 10 days hunting + 10 times upvoting the hunting posts (1 full voting score: 20 poinst)
- Lv.3: Lv.2 + at least 3 times on top 10 hunts (1 full voting score: 30 poinst)
- Lv.4: Lv.2 + at least 5 times on top 10 hunts (1 full voting score: 50 poinst)
- Lv.5: 30 days hunting + 30 times upvoting the hunting posts + at least 10 times on top 10 hunts. (1 full voting score: 100 poinst)
The Lv can be downgraded if the hunter does not have any hunting or voting activities more than 10 days. (Lv 5 -> Lv 4 -> ...)

-------------------------------

- I think it is unfair for others who already started the platform last month. If these terms are implemented we should start from the bottom (top 10 hunts) will be reset.

- Everybody should start from Lv0 - lv2 

- There should not also be downgrading of levels since steemit is wide, some don't use steemhunt everyday. Some just wants to share their hunt because they like it and continue to do what they want.

**Comment by sydneyitguy** [comment]
@chuuuckie thanks for sharing your thoughts:)

**Comment by sydneyitguy** [comment]
I'd like to share our thought about implementing the ABV algorithm. Changed quite a bit so far.

### 1. For the white-list (to become level 1) - we'll use 2 conditions. 
   1) The user need to be Steemhunt user (curation trail doesn't count)
   2) Steemit Reputation should be at least 35 (this is for filtering out alt accounts created for manual civil attacks)

### 2. Level by "Hunt Curation Score (HCS)"
The only thing that affects on HCS is how much  **curation effort you put in into Steemhunt**.

**It doesn't matter:**
     1) how much Steem Power you have
     2) how many postings you made on Steemhunt
     3) ranking of the postings you voted on

**The only thing that matter is:**
The voting weight you used on Steemhunt curation.

If you vote on hunt postings 10 times with 50% voting weight, you spend 500% voting weight in total.
Then your hunt score will be increased by 500 for that day.

*1. You can earn maximum 1000 HCS per day*
*2. If you don't have any voting activity on that day, you'll loose 10 HCS per day*

| Level | Voting Range | Conditions (HCS scores) |
|-------|--------------|------------|
Lv.0 | 0 - 0 | all users |
Lv.1 | 1 - 10 | Steemhunt user + Steemit Rep +35 |
Lv.2 | 1 - 20 | 3,000 HCS |
Lv.3 | 1 - 30 | 10,000 HCS |
Lv.4 | 1 - 50 | 30,000 HCS |
Lv.5 | 1 - 100 | 100,000 HCS |

**Comment by Chuuuckie** [comment]
Sorry, but our Curation Trail is an Automatic vote for most of Cebu/Philippines steemians. It is because they followed the trail and most of our members delegated to the account @steemph.cebu . There must be another way.

**Comment by sydneyitguy** [comment]
@Chuuuckie 
We're not (officially) against curation trail or bidbot, subscription bot, etc.

ABV and HCS leveling stuff is purely for increasing the curation quality on Steemhunt ranking board.
If someone vote on postings just because "someone else voted", I don't think it's a valid voting for the content.

**Comment by zionopia** [comment]
Can a Lv.0 become Lv.2 without achieving Lv.1?
Additionally, is as example a Lv. 5 going back to Lv.0 if the Steemit Rep is going under 35 (flag) (after the user reached Lv.5 in Steemhunt)

Burning Rate : If you upvote for 1 day it will take 100 days to get this HCS gone. This is a ratio of 1:100. I think that is quite slow, but is IMHO.

Lv. 5 can be reached in about 3 1/2 month permanent active use, which means in reality about 6 month, is fair from my view of point.

**Comment by sydneyitguy** [comment]
@zionopia Thanks for your thought! It helps a lot

1. an a Lv.0 become Lv.2 without achieving Lv.1? => Yes if someone already have over 3000HCS, and just made the rep 35 conditions.

2.  Lv. 5 going back to Lv.0  if the Steemit Rep is going under 35 (flag) => Yes

3. Yes I think the burning rate is too small as well. Maybe we should make it bigger.. maybe 50?

**Comment by sydneyitguy** [comment]
We discussed about some edge cases as well.

You can vote with 100% weight indefinitely on Steem, because weight dilutes 2% of your "current voting power".

For example, 
A user is lv 1 and vote with 100% weight - that counts as 10 on SH and if that user just vote every post on SH, this is not really a "big issue" because that's equal to he didn't vote on any post.
However, it's still a little bit of a problem because one user can vote on like 99 of the content to getting the same effect with 1 post down-voted.

There's no way to prevent that on Steem atm (there's dust threshold, but that affects on very small account), so we're thinking a HCS penalty if user vote too many on one day.

For example,
If a user vote 1000% in total, he get's the maximum HCS for that day (1000 HCS)
If a user vote 1500% in total.. maybe that's fine
If a user vote 2000% in total.. yeah we think it's abusing
If a user vote 2100% in total, we deducts HCS for that day by -100 => 900HCS
If a user vote 3000% in total, he's earning becomes 0
If a user don't stop and vote 5000% a day, he's HCS score will be -2000
so on..

and if a user has minus HCS => become lv 0.

**Comment by cyh76507707** [comment]
[Interfaces required]

* Main view: ABV score, aggregation of other counts into symbols, slider bar (voting range), tooltip (explanations)
* On Hunting Post: ABV button and aggregation of other info
* Profile button tap: Add daily accumulated HCS
* On Profile: Add hunter level, HCS
* Re-arrange the filter (sort by)

**Comment by cyh76507707** [comment]
Very rough graph that shows how much you can accumulate your HCS everyday.

1. [Plus HCS] So, the basic rule is that you can have plus HCS only upto 1000% (For example, you upvoted 10 times with 100% full vote today, your accumulated HCS today is 1000). 
2. [Buffer] If you keep upvoting after you reached over 1000%, your HCS won't change until you reach 2000%.
3. [Minus/Penalty HCS] After you reached 2000% and you keep upvoting more hunts at the same day, we consider this attempt as an abusive behaviours. Then, your HCS will decreased by additional vp used after 2000% (For example, when your total vp used reached 2500%, you will have -500 penalty HCS. So your final HCS score you earn will be just 500 HCS (1000-500). If you constantly keep upvoting even more, so you reached total 3000% vp used today, you earn zero HCS at the day (1000-1000). If you keep doing the upvoting even more?? then your earned HCS can be minus...)

This is a simple chart to explain this reputation score system.
![png image-9a42483b5d8b-1](https://user-images.githubusercontent.com/15100667/41178127-3df2f792-6b5e-11e8-87fc-1059170fbddc.png)

**Comment by cyh76507707** [comment]
* The most important action on SH is "Upvoting."
* HCS is based on how you upvoting on hunter's posts.
* If you don't curate any hunting posts (upvoting), you will loose -100 HCS at the day.
* The upvoting MUST be made on SH website.

**Comment by sydneyitguy** [comment]
maybe a relative score brackets?

| lv5 | lv4 | lv3 | lv2 | lv1 |
|----|----|----|----|----|
|5% | 20% | 40% | 70% | 100% |

**Comment by sydneyitguy** [comment]
Maybe.. simple is the best

Reputation:
* ~ 34 => voting weight x 0
* 35 ~ 44 => x0.5
* 45 ~ 54 => x1
* 55 ~ 59 => x2
* 60 ~ 69 => x 3
* 70 ~ 80 => x4

**Comment by cyh76507707** [comment]
Reputation Distributions on Steemit
https://steemit.com/steem/@steemreports/steem-reputation-distribution-charts

**Comment by zionopia** [comment]
Assuming that the HCS system will be implemented as mentioned (Lv.0 ~ Lv.5) and the Reputation weight is going to count, I can simulate following edge scenario.

1. Steem Rep. 60, HCS Lv. 5, 100% voting = 300 (top edge)
2. Steem Rep. 45, HCS Lv. 3 100% voting = 30 (medium)
3. Steem Rep. 35, HCS Lv. 1 100% voting = 5 (bottom edge)

This is a factor of 60x from bottom to the edge. This is going to be finetuning the numbers but just wanted to show the edges. From my point of view keeping the alternative accounts out of the game is a good strategy, but it may have to be considered that the medium and top edge is too far away. Please correct if this simulation is not correct.

**Comment by cyh76507707** [comment]
VCV = Total Voting Counts / Total Voters
- based on past 7 days voting activities
- higher this score, more suspicious to be v4v

**Comment by cyh76507707** [comment]
Separation b/w SH's upvotes to the ranking
- Mods evaluate the hunted product's quality based on 1-5
- Based on the mods' score, SH's upvoting power is decided to the hunt post

**Comment by sydneyitguy** [comment]
https://github.com/Steemhunt/api/commit/784fe89d6404479a01b825d65cb54da916646ca4

**Comment by sydneyitguy** [comment]
We've been tested for a week and half with ABV (voting weight is affected by only Steemit reputations), but that brought a lot of issues.

We solved bidbot, curation trail and other bot ranking manipulation successfully by introducing the whitelist (reputation & DAU filtering).

However, a new issue with a lot of spammers & abusers has arisen as the current version of ABV doesn't require any SP holding or putting effort on Steemhunt itself.

For example, if a user with 55 reputation joined into SH, they immediately have 2.0 voting weight. There were many of user groups who have dozens of user pools (esp Nigeria, Turkey) whose already active users on Steemit with a high reputation and voting each others.

So now we're going to test with 

# ABV version 2.

We'll introduce HCS (Hunt Curation Score) and level concept again with following table:

| Level | Voting Weight | Conditions (Hunt Curation Score) |
|-------|--------------|------------|
Lv.0 | 0 | all users |
Lv.1 | x1 | Steemhunt user + Steemit Rep over 35 |
Lv.2 | x2 | 5,000 HCS |
Lv.3 | x3 | 25,000 HCS |
Lv.4 | x4 | 150,000 HCS |
Lv.5 | x5 | 500,000 HCS | 

You can acquire HCS by votings on Hunt (recent 3 months calculated), and your voting weight and timing is considered.
We use curation weight on Steem BC (it's a mixed value of your VEST and voting timing)

> Steem calculates the "weight" of each vote with a formula using the square root of the voter rshares in relation to the sum of all previous voters rshares. A great explanation of the curation reward system was given by @miniature-tiger in:

>[An Illustrated Guide to Curation - from the simple to the complex - with real examples from past posts - Part 1](https://steemit.com/curation/@miniature-tiger/an-illustrated-guide-to-curation-from-the-simple-to-the-complex-with-real-examples-from-past-posts-part-1)
>[An Illustrated Guide to Curation - from the simple to the complex - with real examples from past posts - Part 2](https://steemit.com/curation/@miniature-tiger/an-illustrated-guide-to-curation-from-the-simple-to-the-complex-with-real-examples-from-past-posts-part-2)

>The core math is the calculation of
>weight = (sqrt(prev_rshares - vote_rshares) - sqrt(prev_rshares)) * [30min-penalty] * [beneficiaries]

![image](https://user-images.githubusercontent.com/1332279/42224109-3ed072d8-7f14-11e8-8154-c5637cd4f6b4.png)

Ref: https://github.com/MattyIce/bottracker/issues/9

## Define 1 HCS as 1,000 voting weight earned
means if you have about 10K SP and full vote on a content on an average timing,
it would be 500K voting weight => you can earn 500 HCS.

Estimated voting contribution for each tier:
- to reach level 2, about $10 worth  of votings on other hunter's hunt postings
- to reach level 3, about $50 worth of votings
- to reach level 4, about $300 worth  of votings
- to reach level 5, about $1000 worth  of  votings

## Other rules
- Only votes on Steemhunt calculated
- Self vote will not be counted
- [Diversity Score (0~1)](https://steemit.com/steemhunt/@steemhunt/steemhunt-s-account-based-voting-ver-2-diversity-score) will be multiplied on your final voting weight
- You can earn maximum 10,000 HCS per day

## Changes in Steemhunt voting support
- All previous votings (hunt posts and review comments) will be stopped
- We vote on users max 1 per account everyday if they posted a hunt or comment (no difference in weight)
- Voting weight is not related to the ranking, it's only related to users level

For example, 
- if user is level 5, we vote on his hunt or comment with 20% weight.
- if user is  level 1, we vote on his hunt or comment with 1% weight.

We believe this voting support mechanism can solve both issues with spams and alt accounts.

## Facts
1. Level up is easier if you have more SP
2. Even if you have a higher level, you have no advantages on your hunt ranking (because self-vote doesn't count)
3. The only way you receive a better voting support from SH is you use your voting power on other hunters on our community (Not by spamming, using bidbots, having voting pools, etc)

**Comment by sydneyitguy** [comment]
Another approach: Dynamic Voting Windows (DVW)
https://github.com/Steemhunt/api/issues/39

**Comment by sydneyitguy** [comment]
Another thought.

Whales tend to vote with lower power on curation, but because SH translate that voting percentage directly into our HCS, their voting influence becomes much lower on SH.

For example, if Hunt Score maximum cap is $10 voting,

1. Same as now, if a fish who has no SP cast 100% voting, it's considered 100% HS 
2. But if a whale who has $100 voting worth cast a 10% voting, it should be considered 100% HS on the posting.

This could be a simpler solution than ABV 2.0, but still effective.

**Comment by sydneyitguy** [comment]
To improve jerk score:

We may have to calculate with the number of hunt they made for a month as well.
Because alt account who doesn't post anything will get 0 JS always.

**Comment by sydneyitguy** [comment]
Few more ideas 

1. Account credibility:
- Facebook authentication - option to add more credibility on the top of current reputation based voting weight

2. Steemit follower / following graph:
- Maybe less weight on friend's votings?

3. Lower ranking penalty
- To minimize low quality content spam from penny pickers

**Comment by sydneyitguy** [comment]
# ABV 2.0 (Draft)
HCS based user level system that inherits all matrix of ABV 1.0.
Major pivot: We'll remove SH upvotes from our ranking board entirely to simplify the community rules and minimize the manual labour (such as blacklisting).

Currently our voting weight calculation is a mess with all different matrix:
- reputation
- influencer boost
- diversity score (mix of voting diversity, circle voting, hunt count, curation count)

Let's refactor them into a more organized way
1. Account Credibility
    - reputation
    - maybe some other methods (account age, follower count, Facebook login, etc)
2. Boost
    - influencers
    - maybe some other groups (team, mods, etc)
3. Curation Score
    - voting diversity (circle votings)
    - total curation weight (count)
4. Hunt Score
    - hunt count
    - based on daily ranking

`User score` is decided by all score combined: e.g. 1 * 2 * 3 * 4

1. `User score` = `Voting weight`.
2. `User level` is based on `User score` using relative scale.

Our voting bot will vote on users content based on the user level instead of hunt ranking (pro/con comments votings will be removed as well).

Max number of votings on content are limited by
- Hunt: 1 time (weight: 10)
- Comments: 10 times (weight: 1)
so every users will have 20 units of votings in total per day.

SH bot's voting weight will be decided by
`content weight x user weight`
and user weight is decided by

| Level | Proportion (Top x% by User Score) | SH voting weight |
|-------|-------|-------|
Lv.5 | 10% | x5 |
Lv.4 | 20% | x4 |
Lv.3 | 35% | x3 |
Lv.2 | 50% | x2 |
Lv.1 | 70% | x1 |
Lv.0 | 100% | x0 |

Our team members (not community based roles) will be excluded from the SH votings.

**Comment by zionopia** [comment]
<h2>Suggestions.</h2>


   * Account Credibility
        - reputation 
          **> could be left unchanged as in ABV 1.0**
         - maybe some other methods 
           **> All time Author SP, Post Count, Post Comments Count, Vote Count, Votes Received coud be elements too**
 
    * Boost
        - influencers
        - maybe some other groups (team, mods, etc)
         **> It would be better to grow the Influencer pool itself as then to widen it to mods or team, etc. If possible team and mods should stay neutral with boosted VW. Temporarily before finding a bigger Influencer pool should be ok.**
  * Curation Score
        - voting diversity (circle votings)
        - total curation weight (count)
   *  Hunt Score
        - hunt count
        - based on daily ranking
         **>this part would be very important to give the ranking still a viable meaning**

<h2>Edge cases</h2>
When there is no scenario that the level is dropping significantly without good activity or only as an example top 100 posts are going to be upvoted, it can happen that when a hunter reaches level 5, it actually doesn`t matter anymore what the hunter hunts. (should be still within the PG, but does not need to be cool anymore)

The huntscore would needed to be applied for a specific time (as the daily ranking is here included as factor), as example for the last month.

Otherwise I could hunt a new little app every single day after getting into level 5 to milk the system constantly without providing any viable content for Steemhunt.

Having calculating the Hunt Score from the last 30 days, as example, would avoid that, as I would still need to have some higher ranked hunts to get into level 5 or keep it there.

**Comment by sydneyitguy** [comment]
@zionopia Thanks for your comment :)

All the data (except account credibility and boost) will be based on recent 30 days activities.

Even if someone reaches on level 5, if they become inactive for few days OR hunt non-cool products that ranked like low 30%, their US(User Score) will be decreased, and level can be dropped as the level grades is relative scale (even if your US increased, your level can still be decreased if others performed better)

**Comment by sydneyitguy** [comment]
I'm deprecating the idea of relative scale due to 2 critical issues below:

1. Level updates can't be in real-time as it requires every users US (User Score) sorted on every activities made. Instead of real-time updates, we could just update once every day before voting time, but if a user was Lv 3 on posting time, but became Lv2 on voting time, they would complain.

2. Actual distribution of US is too much skewed, so Lv.5 (top 10%) is range from 20.0 - 1.40 US. From Lv.4 (Top 20%) - Lv.2 (Top 55%) would be just like 1.40 - 0.1 and there're more than 20% of Lv.0 (US 0.0) users. Absolute scale (US tier) is pretty much decided by the proportion of inactive users. An alternative way is using only DAU data to decide the level tier, but that would cause too much fluctuation on users' level and would make users confused.

By considering all the issues, absolute scaling looks more feasible and suitable way to approach.

## Absolute Scaling

| Level | User Score | SH voting weight |
|-------|-------|-------|
Lv.5 | 8.0 | x5 |
Lv.4 | 5.0 | x4 |
Lv.3 | 3.0 | x3 |
Lv.2 | 2.0 | x2 |
Lv.1 | 1.0 | x1 |
Lv.0 | Lower than 1.0 | x0 |

### Advantages / Disadvantages of absolute scaling:

#### Advantages
- Easier to understand as it's widely used in gaming and other apps
- Can motivate users to increase their US by showing the score graph on their profile (e.g. 0.5 US left till Lv. 2)

#### Disadvantages
- We don't know what's the optimal score tier for each level - this can be tuned / changed by time

**Comment by astrocket** [comment]
![image](https://user-images.githubusercontent.com/18032062/43068159-9c528f5a-8ea4-11e8-8db5-48c2ef7b9be2.png)
@cyh76507707 Here is the sample design for user score level bar.

**Comment by sydneyitguy** [comment]
### User Score (=Voting Power) can be

#### Increased
- When account credibility is increased (higher reputation, older accounts)
- When user login to Steemhunt more frequently
- When user vote on more hunt pots
- When user vote with more weight and earlier timing on hunt posts (same curation penalty applied for the first 30 minutes of posting)
- When user hunted and it's on ranked high
- When user is selected as our community influencer

#### Decreased
- When user's reputation is decreased
- When user doesn't login to Steemhunt less frequently
- When user vote on the same group of people many times
- When user does circle voting with a specific group
- When user hunted and it's on ranked low

**Comment by cyh76507707** [comment]
![profile 2](https://user-images.githubusercontent.com/15100667/43150434-d6a586fe-8f61-11e8-8dbf-c3ecc32fb5ed.jpg)
