### ISSUE TITLE
Add a counter when posting

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#14]
Please add a small counter under the `POST NOW` button to show how much time left till the end of the day. The format can be like this:

`1:32:22 till midnight`

hours:mins:secs -> and it changes on realtime basis.

**Comment by sydneyitguy** [comment]
needs wording

**Comment by cyh76507707** [comment]
Copy edited - 
`8 hours and 21 minutes left for today's ranking, based on KST midnight (GMT + 9).`
