### ISSUE TITLE
New Brand Slogan for Steemhunt

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#145]
As we started Steemhunt project, we have started as "A Steem Fueled Product Hunt" so that people can fast catch what this community aim for. Now we've got great community foundations and number of people who contribute on this project.

I think it is now a great time to change our brand slogan to be more related to what HUNT platform is heading on. Feel free to suggest any great phrases or opinions!

**Comment by cyh76507707** [comment]
**Maybe we can run some SBD bounty competition for this!**

**Comment by dmouseuk** [comment]
>  HUNT THE **BEST** OF THE WEB + EARN **REWARDS**
help us discover the **_most unique_** urls across the web

**Comment by dayleeo** [comment]
ok, not to be the extra one.. but here are a few ideas

> "Share new products, the blockchain way."

> "Hunt new products, the blockchain way."

> "Fresh finds from interesting folks."

> "Be inspired by fresh new products."

> "The best products, ranked daily."

> "Community curated, & Cool AF"

> "Share, upvote and  products"

> "Nothing like that new-tech smell…"

> "Home of the Hunters"

> “Deez Hunts!”

**Comment by ThaBiGGDoGG** [comment]
SteemHunt - How You Earn Tokens
![slogan](https://user-images.githubusercontent.com/38387853/41008648-14347e64-68fa-11e8-8cdd-69bf8b9ab770.png)

**Comment by dmouseuk** [comment]
don't think this should be closed as we had not decided on a new one yet! :)
