### ISSUE TITLE
Wrong number of additional votes if total exceeds 15 votes (NB_SHOW_VOTES)

### ISSUE THREAD

**Issue by espoem** [Steemhunt/web#146]
#### Expected behavior

In case that the displayed votes exceed the threshold, the sum of displayed votes and number of additional votes should be equal to the total number of votes.

#### Actual behavior

The number of additional votes is incorrect.

![image](https://user-images.githubusercontent.com/16621517/40847280-3d470aa6-65bc-11e8-9fc4-e9d4a017e014.png)

Related code: https://github.com/Steemhunt/web/blob/741e2652b3971a4f192227f0538790776f3ef67a/src/components/ContentPayoutAndVotes.js#L50-L54

#### How to reproduce

1. Open a hunt with more than NB_SHOW_VOTES, which means 15
2. Hover over the votes number

* Browser: Chrome 66
* Operating system: Windows 10

**Comment by elizabeth-dev** [comment]
This was apparently fixed at https://github.com/Steemhunt/web/commit/aa87a5001bc46f60e83388fecfc90d824cd9c4ed

**Comment by sydneyitguy** [comment]
@elizabeth-dev thanks :)
