### ISSUE TITLE
Moderator stats / payout report

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#151]
total posts, verified count by mods, hidden count by mods, etc

**Comment by cyh76507707** [comment]
Let's prepare to run the moderator payout report, or the log sharing with community members like DLive and Utopian.

* DLive - https://steemit.com/dlive/@teamdlive/dlive-or-transparency-report-3-june-3-2018
* Utopian - https://steemit.com/utopian-io/@utopian.stats/utopian-pay-2018-3-29
