### ISSUE TITLE
Header of the submissions cover the scrollbar at the top, which prohibits scrolling by dragging

### ISSUE THREAD

**Issue by espoem** [Steemhunt/web#153]
#### Expected behavior

The right panel shows the daily hunts. It is expected that the site can be scrolled by dragging of the scrollbar.

#### Actual behavior

It is not possible to drag the scrollbar at the top since the header covers it.

![image](https://user-images.githubusercontent.com/16621517/40996211-8cdfff30-6901-11e8-95f6-e74e32a3d054.png)

#### How to reproduce

1. Open steemhunt homepage with hunts
2. Try to drag the scrollbar from the top

* Browser: Chrome 66
* Operating system: Windows 10

**Comment by sydneyitguy** [comment]
Oh thanks for the detailed reporting!
I didn’t know because I use mac only. Will fix this :) 👍🏻

**Comment by astrocket** [comment]
Fixed.
