### ISSUE TITLE
Show hidden posts on the hunter's profile

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#157]
This is a request by some hunter.
- When the hunter's post being hidden, he or she should be able to see the hidden post on the profile page.

**Comment by 4Ykw** [comment]
I am seeing this already. Not sure why the post is showing "hidden" or if what I am seeing is that behaviour. Here is the shot I see:

![image](https://user-images.githubusercontent.com/6281545/42130861-958a1f8c-7d45-11e8-9c0b-211fa0273310.png)

**Comment by astrocket** [comment]
Closing this issue, b/c it's an already implemented feature.
