### ISSUE TITLE
Search results heading is too close to the middle scrollbar

### ISSUE THREAD

**Issue by espoem** [Steemhunt/web#159]
#### Expected behavior

There should be padding between the scrollbar and the heading just like when a user does not search for anything.

![image](https://user-images.githubusercontent.com/16621517/41064333-8e9f3108-69db-11e8-99fa-27a996af4fb9.png)

#### Actual behavior

When user search for a hunt, the heading of the results is too close to the middle scrollbar.

![image](https://user-images.githubusercontent.com/16621517/41064381-ae701790-69db-11e8-8bd3-f41ca62ff06b.png)

#### How to reproduce

1. Search for a hunt

* Browser: Chrome 66
* Operating system: Windows 10

**Comment by cyh76507707** [comment]
Thanks so much for your report!

**Comment by sydneyitguy** [comment]
fixed
