### ISSUE TITLE
Add "Guides" tab on the profile section

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#160]
suggested by @meditateonthat:

*"Can you make PG available from steemhunt.com website, easily accessible. I looked all over these threads and can't find more than pieces. STORY: As a visitor of the steemhunt.com site, both logged in and not logged in, I would like to quickly and easily access the latest Post Guidelines from any page on the site."*

We can make a new button tab called "Guides" in the profile section (when a user click the profile picture), and redirect to the Posting Guidelines doc.

**Comment by astrocket** [comment]
https://github.com/Steemhunt/web/blob/master/POSTING_GUIDELINES.md
