### ISSUE TITLE
Issues uploading main image on post

### ISSUE THREAD

**Issue by Nicknyr** [Steemhunt/web#161]
I am attempting to post my first post on SteemHunt.

I've uploaded pictures both in the Hunter's comments section and also the image section. The images in the comments section I've uploaded via Imgur and work fine, but the main image that is uploaded via click or drag within the editor doesn't work.

I click add an image and I select the image I want and the preview displays in the editor but the image doesn't display as the main image on the post preview. 

I try to submit my post and I get an error "Please upload at least one image"

**Comment by Folken8** [comment]
Hello,

On which plateform? Mobile or desktop? 
Windows or Mac? 
What browser?

**Comment by sydneyitguy** [comment]
needs clarification for the environment.
it's working on most of major browsers & mobile, so i'll close this issue for now.
