### ISSUE TITLE
[MODERATE COMMENT REVIEWS] [SUGGESTION]

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/web#165]
Instead of Lottery Comments why not we Moderate comment reviews for each approved hunt.

[PROBLEMS]

As reviewing and commenting each hunt I like with love and passion. I see users who are still abusing the system, in fact I even found a user who pretends to know what gadget that is,

Comments who get upvoted are those who are not helpful enough. I have seen review comments that inclines with my background like video cameras and action camera, and I found a comment which is not convincing for a review comment like that. 

[SOLUTION]

- Each review hunt must be approved by a moderator (I know it takes time and add a few moderators to do so, lets think about the quality of post not just leave a comment and consider it a lottery ticket)

- If 100 will be considered for an upvote, then top 1-100 will be considered to get an upvote
This will minimize the Top 1-10 to get more comments and upvotes but instead look for another hunt which it also is interesting to find.
This will also let the hunters not just upvote 50% - 100% those who already got a bigger rating

**Comment by cyh76507707** [comment]
Thanks for your opinion. By the way, yes we are discussing to moderate the review comments too with our new review comment interface. You can add up your opinion on this issue ticket.

https://github.com/Steemhunt/web/issues/56

I will close this issue :)
