### ISSUE TITLE
Cannot view the Stemhunt.com about page fully in Landscape mode. 

### ISSUE THREAD

**Issue by iamowomizz** [Steemhunt/web#166]
**Expected Behaviour**
When i rotate my phone to landscape mode and i click on the ? Button on steemhunt.com i expected to be able to see the steemhunt about page fully.

**Actual Behaviour**
When i rotate my phone to landscape mode and i click on the ? Button on steemhunt.com i can not see the steem hunt about page fully.

**How To Reproduce**
* go to steemhunt.com
* rotate you phone to landscape mode
* a ? button appears between search button and the create new post button
* click on the ? button and you will get taken to the steem hunt about page.
* scroll down the page and you'll see the page dosen't display fully.
* Broswer: Chrome Version 66.0.3359.158
* Operating System: Android 7.0 (steemhunt Mobile website version)

**Recording Of the Bug**
https://youtu.be/78HLOR9NSjg

**Comment by superoo7** [comment]
@iamowomizz 
can you list what type of phone you are using and the dimensions of it?
so that it can be reproduce on chrome tools on desktop

**Comment by astrocket** [comment]
We decide view point based on the screen width. The issue you mentioned is a natural behavior for most mobile phones.

```css
@else if $media == tablet { // 1 column
  @media only screen and (max-width: 1023px) { @content; }
}
```
