### ISSUE TITLE
SH Upvoting only for Top 100 Hunts

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#172]
[Problem]
* There are too many hunting posts everyday.
* This reduces good hunting posts to be observed well.
* Too many hunting posts decrease the lower ranking rewards.

[Solution]
* Steemhunt upvotes only for the top 100 hunts.
* Maintain the same reverse-distribution upvoting algorithm.

**Comment by astrocket** [comment]
Fixed since ABV 2.0
