### ISSUE TITLE
Search issue when there is a "." 

### ISSUE THREAD

**Issue by Folken8** [Steemhunt/web#176]
#### Expected behavior

When we are looking for products like "Vinci 2.0", we should exceptct to find the product here: https://steemhunt.com/@rizkydemora/vinci-2-0-world-s-first-standalone-smart-headphone

#### Actual behavior
When we make a search that include a ".", the search don't work. This is a problem when the name of the product is the website himself. (Example ToVid.Io -> https://steemhunt.com/@aschatria/tovid-io-free-online-youtube-image-and-audio-editor-and-publisher ), because even if you type "tovid" the search won't work. 

#### How to reproduce

You can try 'Vinci 2.0' -> won't work but 'Vinci' will work
You can try ToVid.Io -> won't work and also 'ToVid' won't work because there is no space.

**Comment by astrocket** [comment]
Already fixed.
