### ISSUE TITLE
Found bug in Steemhunt #02

### ISSUE THREAD

**Issue by Farhanali306** [Steemhunt/web#184]
## Expected behavior

In Steemhunt.com when opening anyone Steemhunt user profile then It will show all the correct information about that personal account.

## Actual behavior

When I opened Steemhunt user account then the webpage was not showing correct information about that User

## How to reproduce

- Go to SteemHunt Website Click [Here](https://steemhunt.com)
- Login into your account if haven't account for signup Click [Here](https://signup.steemit.com/?ref=steemhunt)
- Now select any product
- Now goto to any one account you may directly open anyone account but I'm using this way.
- Now Scroll down and see Information about the user.

## Recording Of The Bug

![Animation1.gif](https://cdn.steemitimages.com/DQmYP8LoB2hAYgHfEm8NFD9ZCkJivxJ2JhMwDewqcChiE7A/Animation1.gif)

**Comment by superoo7** [comment]
Thanks for reporting, I had done a Pull Request to fix that https://github.com/Steemhunt/web/pull/188

**Comment by sydneyitguy** [comment]
hum.. it was actually changed for displaying "Steemhunt joined date", but was null as we didn't fetch the user data except my own profile.

created filed is " Steemit joined date"

I guess this information is not important anyway, and confusing, so I'll just delete that row completely.

Thanks for your contribution!
