### ISSUE TITLE
[COMMENT REVIEW ABUSE MUST MODERATE COMMENTS]

### ISSUE THREAD

**Issue by Chuuuckie** [Steemhunt/web#186]
![image](https://user-images.githubusercontent.com/36227271/41430029-78fb08ec-7041-11e8-8c03-8b2314ce9b65.png)

This is a bad example. Copy/Pasting, Comments should be moderated.

**Comment by sydneyitguy** [comment]
Moderation on review comments is probably not possible as we may need 3x more moderators than now to cover them (& managing mods quality is also become a problem in that scale)

We decided that we'll run #report-plagiarism channel on our Discord, so we can blacklist users and give bounty to reporters.

Thanks!
