### ISSUE TITLE
Steemhunt asks to reconnect with steemconnnect when changing mobile view to desktop or mobile version

### ISSUE THREAD

**Issue by shaphir** [Steemhunt/web#193]
Hello developers.

Today I experienced a behavior that made me a little annoyed, when I try to change the mobile view to the desktop version or to the mobile version, I am prompted to reconnect with steemconnect.

Note:
Note:
To find this behavior you must log out of steemhunt first ( If you have logged in before).

#### Steps to get behavior
* Go to https://steemhunt.com
* Login using steemconnect
* Change mobile view to desktop or mobile version
* Browser : Google chrome: fast & secure version 67.0.3396.87
* Opening sistem: Oppo A57 android version 6.0.1

Below is a screen recording of my phone when I get the behavior.
Watch the video on youtube  https://youtu.be/MjbzjKUMMbk

**Comment by sydneyitguy** [comment]
duplicated issue with - https://github.com/Steemhunt/web/issues/152
