### ISSUE TITLE
Bug: Existing product link searching is not working in case of google play store product link

### ISSUE THREAD

**Issue by sourovafrin** [Steemhunt/web#196]
#### Expected behavior

At the time of posting on steemhunt we need to put the product link on the `Product link` box.
When we put the link on the box, steemhunt automatically check if someone has posted this link before or not.
It shows existing post link if steemhunt find it. And this should work with all website's link

#### Actual behavior

Steemhunt is not showing existing post for google play store link or can be said it is not working in case of google play store link.
For this reason my 1st post done on steemhunt was disapproved as the product link was from google play store and steemhunt was unable to find the existing post link.

#### How to reproduce

- First of all search for a product on steemhunt which link is from google play store.

- Now copy the product  link from the post and clear `&ref=steemhunt` from the end of the link as steemhunt automatically create it. 

- Now go to post creation page or click [here](https://steemhunt.com/post) for direct land.

- Put the link in the `Product link` box.

- You will see that it will load for a while and will give no result

* Browser version: Chrome Version 67.0.3396.79 (Official Build) (64-bit)

* Operating system: Windows 8.1

I have tested on these posts-

- Post [link](https://steemhunt.com/@urbangladiator/partiko-android-app-for-the-steem-blockchain) ; Product [link](https://play.google.com/store/apps/details?id=io.partiko.android0)
- Post [link](https://steemhunt.com/@urbangladiator/steemia-mobile-app-for-the-steem-blockchain) ; Product [link](https://play.google.com/store/apps/details?id=com.steemia.steemia&hl=be)
- Post [link](https://steemhunt.com/@rangertx/super-8-ball-club-steem-app-gaming-pool-app-pays-you-in-steem-when-you-win) ; Product [link](https://play.google.com/store/apps/details?id=com.creativestudio.super8ballclub)

#### Recording Of The Bug

https://youtu.be/jikNh1GYQX4

**Comment by sydneyitguy** [comment]
Fixed - https://github.com/Steemhunt/api/commit/921f02df62c971f98b894415c12dc322959ad3fb
