### ISSUE TITLE
it want login access again when switching to desktop mode

### ISSUE THREAD

**Issue by shihann14** [Steemhunt/web#197]
* Repository: https://github.com/Steemhunt/web

* Project Name: Steemhunt

* Expected behavior
Steemhunt.com should not be want login access again when switching the view to desktop mode.

* Actual behavior
when i logging in on Steemhunt.com the website requests login access again when switching the view to desktop mode.

* How to reproduce
1.go to the Steemhunt.com link : Steemhunt.com

2.Login with your steemit account.

3 . After login, switch your browser mode to desktop mode, then the web will request login access again.

>Browser/App version: Google Chrome (67.0.3396.68 Version)
Operating system: android 7.0

*  recording of the bug:  https://youtu.be/TnPg3LInFxA

**Comment by sourovafrin** [comment]
Check open and closed issues before you submit a issue.
Issues submitted before- #152 and #193

**Comment by sydneyitguy** [comment]
merge with https://github.com/Steemhunt/web/issues/152
