### ISSUE TITLE
Error when giving a vote on post

### ISSUE THREAD

**Issue by zaid222** [Steemhunt/web#199]
#### Expected behavior
should after I vote on someone else's post, my account name is visible on the voting list

#### Actual behavior
after I vote on someone else's post, my account name is not visible and does not increase on the vote list, while the red mark on the vote icon is already visible, indicating my vote is successful, but my account name is not visible on the list

#### How to reproduce
* Open Google chrome
* Serching SteemHunt 
* Login use a steemconnect
* Click icon Vote  
* See bug

>Browser: GoogleChrome v.67.0.3396.87
Operating system: Android 6.0

#### Recording of the bug

https://m.youtube.com/watch?v=Tg2lNdFKXhw

**Comment by sydneyitguy** [comment]
This is not a bug.
On Steem, you can still vote on posts that's already paid out (after 7 days), but that voting just doesn't add any value on the post or reduce your voting weight.

On Steemhunt, it's similar - you can still cast your vote on old posts, but that voting isn't counted as a valid voting.
