### ISSUE TITLE
Suggestion: Add 2 category for user's posts and show pending for unreviewed post

### ISSUE THREAD

**Issue by sourovafrin** [Steemhunt/web#200]
Now we can only see those post on our profile which are on pending or approved.
After getting a post disapproved, system hide the post from user's profile.
But we can still access it by directly clicking on that disapproved post link.
The post is available on steemhunt but not showing on user's profile. Doesn't it seem weird?

Possible fix-
You can add three category on user's proifle.
1- Approved post
2- Disapproved post

Approved post category can be the default user's profile page, ex: `https://steemhunt.com/author/@sourovafrin`

The disapproved category will show disproved post. link ex: `https://steemhunt.com/author/@sourovafrin/disapproved`

And the last thing is adding a pending button beside the post which is pending. Example: Issue #195 . This was for mod, and can be implemented in case of pending post.
If this feature added, user don't need to check comment every time to check if mod reviewed his post or not.

**Comment by sydneyitguy** [comment]
For this one, I just made hidden posts visible on users' profile page.
https://github.com/Steemhunt/api/commit/f473784370b87e69f85dc28c4823d46ce18016b6

Thanks for your suggestion :)

**Comment by sourovafrin** [comment]
Can you also add a flag button so that user can flag comment abusers?
