### ISSUE TITLE
No opacity for downvoted mod comments

### ISSUE THREAD

**Issue by fknmayhem** [Steemhunt/web#204]
#### Expected behavior

Moderator comments have to be always visible and be highlighted in the Steemhunt comments. When a user downvotes a mod comment for which ever reason, the mod comment should still be highly visible. Especially before the ranking window closes and/or the bot passes.

#### Actual behavior

Downvoted mods comments become less clear when negative threshold.

#### How to reproduce

Downvote a freshly posted mod comment.

##### Additional suggestion

On Steemhunt mod comments could additionally be placed at the top of the comments [at least until ranking window closes].

**Comment by sydneyitguy** [comment]
what mod comment has been downvoted?
