### ISSUE TITLE
Bug: Scroll bar placed on right side is not working when it is on top of the search bar on steemhunt

### ISSUE THREAD

**Issue by sourovafrin** [Steemhunt/web#209]
#### Expected behavior

On steemhunt there is two scroll bar.
One is on the middle which helps to scroll while reading post. And another one is on the right side which helps to scroll post list. Both should work correctly on every position. 

#### Actual behavior

Though the middle  scroll bar is working but the scroll bar placed on right side is not working when it is on top of the search bar.
Generally when we place mouse on scroll bar it turns into a dark color which is working in case of post middle one.
But it is not responding in case of right side bar.

#### How to reproduce

- Go to [steemhunt](https://steemhunt.com) and there you will see both scroll bar

- Now try to scroll by those bar

- You will see that though middle one is working but right side's scroll bar is not working/responding

**You must check keeping the bar on top of the search bar while reproducing**

* Browser version: Chrome Version 67.0.3396.79 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Possible fix

This can be fixed by simply doing some change in css.

**I am providing a gif of the issue**

![Rec-2018-06-23-11-38-14.gif](https://cdn.steemitimages.com/DQmd9ZhTLcnjFXGVV7WVd5R22JCrKaDWxMZfYfBVZE7jnsf/Rec-2018-06-23-11-38-14.gif)

**Comment by sydneyitguy** [comment]
duplicated - https://github.com/Steemhunt/web/issues/153
