### ISSUE TITLE
Steemhunt- An Account Voting Power On Steemhunt - Doesn't Correspond With Other Voting Power CheTools

### ISSUE THREAD

**Issue by realrufans** [Steemhunt/web#210]
#### Expected behavior
The percentage ( % ) voting power of an account on Steemhunt should be equivalent to any other tool used for checking voting power.

#### Actual behavior
Voting power on Steemhunt is always lesser than the actual voting power

**Voting power of two accounts on three different websites**

![IMG-20180623-WA0002.jpg](https://cdn.steemitimages.com/DQmPhr7aDqCpPWG8dbPgZdBXQaXddvswcygmWMV4wj57guU/IMG-20180623-WA0002.jpg) 
<sup>Rufans voting power on steemnow</sup>

![IMG-20180623-WA0005.jpg](https://cdn.steemitimages.com/DQmWQzHwxmfwySkYtbBsqtFRMGeBj3DbQGCUm8iACS7GnWr/IMG-20180623-WA0005.jpg)
<sup>Steemhunt voting power on steemnow</sup>

![IMG-20180623-WA0003.jpg](https://cdn.steemitimages.com/DQmZbk4T71R7A4VDrdWCV7yZr4YTgvpLCnyMLsoUyshvaxk/IMG-20180623-WA0003.jpg)
<sup>Rufans voting power on steemd</sup>

![IMG-20180623-WA0004.jpg](https://cdn.steemitimages.com/DQmZCNGe1T4vfKxVirH1AtTawuYK6eZ2J73XumbgsDAh6Bn/IMG-20180623-WA0004.jpg)
<sup>Steemhunt voting power on steemd</sup>

![IMG-20180623-WA0006.jpg](https://cdn.steemitimages.com/DQma7xWRDJ9bSShHNs398jbzU8ih5bC9RozSYK6s3Xrtdk7/IMG-20180623-WA0006.jpg)
<sup>Rufans voting power on steemhunt</sup>

![IMG-20180623-WA0007.jpg](https://cdn.steemitimages.com/DQmT6nLFXRuUt3neRkpvhhL9eD4rZZ3ssZ3seURN1JKTyRZ/IMG-20180623-WA0007.jpg)
<sup>Steemhunt voting power on steemhunt</sup>

From the images above, the two accounts voting power on steemhunt doesn't correspond on with other tools.

My voting power can't be 89% because I haven't been voting anything lately.

#### How to reproduce
 * Go to steemd.com/@rufans
* Check for the account voting power, note it.
* Go steemhunt.com/author/@rufans
* Now compare the voting power.

* Browser/App version: Chrome 67.0.3396.87
* Operating system: Android 0

#### Recording Of The Bug
https://youtu.be/Uz5UYNQ7HGk

**Comment by sydneyitguy** [comment]
Merged with https://github.com/Steemhunt/web/issues/141
