### ISSUE TITLE
End Active Window Hunts 3 Hours Before End of Voting Window

### ISSUE THREAD

**Issue by fknmayhem** [Steemhunt/web#211]
**Suggestion**

In order to allow everyone a minimum amount of time to gather votes, let hunts submitted after 21.00KST roll over to the next. Even if reviewed and approved already.

This gives hunters whose life may not allow them to post at more ideal times, a fairer chance to also gather upvotes.

**TL;DR**: Hunt submission window ends at 21.00KST, voting window ends at midnight KST.

**Comment by shaphir** [comment]
I agree a with you 👍

**Comment by sydneyitguy** [comment]
Requires auto-cleanup of old posts (over 24 hours) as well

**Comment by sydneyitguy** [comment]
ok.. seems 3 hours interface disabling (a work-around easier implementation) method is not ideal.
so I'll just revert my previous change and will stick with the original suggestion here.

**Comment by fknmayhem** [comment]
I think this can be closed.
