### ISSUE TITLE
The "Sort by: Vote Count" button does not work as it should.

### ISSUE THREAD

**Issue by alejandrofz** [Steemhunt/web#215]
#### Expected behavior

Like the other 5 buttons, Ramdon, hunting score, payment value, new and comments count. The Count votes button should sort the publications in descending order, from which you received the most votes, to the one that received the least.

#### Actual behavior

The vote counting button only correctly organizes the first 3 or 4 publications, then its ordering method that shows the publications with a smaller comment number and then a larger one.

#### How to reproduce

1. Open Google Chrome.
2. Then go to www.Steemhunt.com and start the section with your Steem account.
3. Press the "Sort by: Vote Count" button and observe how the publications are not ordered correctly.

#### Equipment used.

* Browser: Navegador: Google Chrome Versión 67.0.3396.87 (Build oficial) (32 bits)
* Operating system: Windows 7 Ultimate

#### Error recording.

https://youtu.be/rNf1zcCptgE

**Comment by sydneyitguy** [comment]
https://github.com/Steemhunt/api/commit/d9082c1462b46473f11bb8e918763d9bf7dd84e5
