### ISSUE TITLE
Minimum-width for comment thread views.

### ISSUE THREAD

**Issue by fknmayhem** [Steemhunt/web#216]
![88d8874b-f658-420e-b5ef-7382643f23bf](https://user-images.githubusercontent.com/40312807/41893594-e18cc632-794e-11e8-8205-1a8c064f49e4.jpeg)

Comment threads should have a minimum-width rather than follow the Steemit model where comments become ultra narrow.

This may require setting a maximum level of two for comment threads, and after that show each next reply in the same thread level. Similar to how busy.org does.

**Comment by sydneyitguy** [comment]
Merged with https://github.com/Steemhunt/web/issues/124
