### ISSUE TITLE
Firefox  issue

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#222]
reported by @oli

"steemhunt does not seem to work with Mozilla Firefox (here version 61; OS: arch linux).

The image upload does not work and the menu is only partially displayed.

Google Chrome, on the other hand, seems to work perfectly."

**Comment by jinzocode** [comment]
I would like to add more information about this issue.
actually this is isn't a bug in steemhunt front-end it seems to be a DNS issue with imgur.com because steemhunt uses it when upload the images. I had the same issue and tried using proxy on Firefox 61 and it works fine.

Hope this helps.

**Comment by shaphir** [comment]
Reported by @flauwy
Hey Hunters, I have a bug to report: With the Brave Browser based on Chrome I have the effect that watching fullscreen Youtube videos from Steemhunt posts makes the browser not react anymore. This does not happen with Firefox.
It happens when I try to close the fullscreen mode.

**Comment by sydneyitguy** [comment]
Checked with Mac + 61.0.1 (64-bit), and everything works fine.
Need to test windows / linux version.

Image upload issue is probably a network issue.
There are few countries block Imgur entirely, test if you can access: http://imgur.com/
If not, you have to use VPN as a work around for now.

We're planning to build our own image server on AWS later (#47)
