### ISSUE TITLE
.DS_Store file available publicly on [steemhunt.com]

### ISSUE THREAD

**Issue by neutrinoguy** [Steemhunt/web#224]
#### Expected behavior
On requesting https://steemhunt.com/.DS_Store it should show 403 forbidden page.

#### Actual behavior

On requesting https://steemhunt.com/.DS_Store it downloads the .DS_store file.

#### How to reproduce

1) Visit https://steemhunt.com/.DS_Store and download file locally.

2) In terminal use the following commnad to view the contents of DS_store file.

`xxd -p path/to/.DS_Store | sed 's/00//g' | tr -d '\n' | sed 's/\([0-9A-F]\{2\}\)/0x\1 /g' | xxd -r -p | strings | sed 's/ptb[LN]ustr//g'
`

* Browser: Google Chrome 
* Operating system: macOS High Sierra ( For command Linux or MacOS to view file)
* Steps to reproduce: wget  https://steemhunt.com/.DS_Store can also work as well.

**Comment by sydneyitguy** [comment]
thanks a lot for pointing that out 👍
