### ISSUE TITLE
A category landing page

### ISSUE THREAD

**Issue by onos1** [Steemhunt/web#225]
When posting a product, it's better hunters select a category they hunting on, e.g iOS apps, android apps, home techs, soccer equipment, others etc,.

Some reasonable achievements I think this might help with :
- when someone enters the site, they can go to a category they like and look for products they need not wandering around 
- it might solve the issue of top people remaining there, if I visit a category I like and vote, even when toggled to hunter score, I have idea of only that category.
- hunters can have a niche of products they hunt, and also voters, not any random scattered products on the opening page.

**Comment by sydneyitguy** [comment]
will be merged with #62
