### ISSUE TITLE
Steemhunt.com sometimes asks me to login when I want to post

### ISSUE THREAD

**Issue by shaphir** [Steemhunt/web#229]
#### Actual behavior
Before I've already logged into steemhunt.com, but they keep asking me to login when I want to post to be posted.
See video recording problem on youtube https://youtu.be/1p6ncEtGPR8

* Browser: Google Chore fast & secure version 67.0.3396.87

* Operating system: Android 6.0.1

**Comment by sydneyitguy** [comment]
It's when Steem blockchain is unstable - login sessions can't be refreshed properly.
Will  check whether there's a better way to handle this error
