### ISSUE TITLE
When you edit the votes, the vote weight meter counts it as another vote.

### ISSUE THREAD

**Issue by alejandrofz** [Steemhunt/web#233]
#### Expected behavior

When you vote for a publication and then want to edit it for personal reasons, SteemHunt should also edit your voting weight without discounting it again.

And in the case of wanting to eliminate the vote, SteemHunt should replenish the weight of vote that was spent when voting on that publication.

#### Actual behavior

In the case of wanting to edit the vote of a publication, Steemhunt discounted again the percentage of your vote weight.

And if you eliminate it does not replace the weight of vote that you used in that publication, so I think you should solve that problem because that error makes the weight of the vote go down much faster than it should and directly affects the weight of the vote total since now it works through a system of vote diversification (Gini-Simpson Method)

#### How to reproduce

https://youtu.be/ETWnNUTzqpk

* Steps to reproduce:
1. Enter SteemHunt.com, check your current voting weight and then vote on any publication.
2. Review your voting weight again and try to edit or delete the vote.

**Comment by sydneyitguy** [comment]
@alejandrofz 
This is not an issue on Steemhunt.
Voting weight doesn't recharge back even if you cancel the vote.
That's the rule built in Steem blockchain.
