### ISSUE TITLE
Suggestion: The upvote value of the steemhunt bot is given by a professional moderator

### ISSUE THREAD

**Issue by shaphir** [Steemhunt/web#235]
I have seen many cool products but do not have decent upvote values from the steemhunt bot. maybe it's due to cheating of the product hunter in any way. I suggest what if the upvote score of the hunt itself is given by a moderator who verifies the hunt!

**Comment by onos1** [comment]
It's community base project not moderators base project.... If you want this utopian-io is waiting

**Comment by fknmayhem** [comment]
@shaphir, Steemhunt doesn’t want to be that centralized site where few only decide over the “cool”.

**Comment by sydneyitguy** [comment]
Thanks for the suggestion @shaphir, but as explained by @fknmayhem SH is a curation community not a curation service.
