### ISSUE TITLE
Steemhunt.com did not forbid me when I hit the add post button, even though I already posted 2 products today, happens when I'm in the wallet page 

### ISSUE THREAD

**Issue by shaphir** [Steemhunt/web#241]
#### Expected behavior
When I clicked the add post button, they should show me the message ```You have already posted 2 products today. Please hunt more tomorrow :)```

#### Actual behavior
Today i have posted 2 products [here](https://steemhunt.com/@shaphir/fedora-less-setup-more-iinnovation) and [here](https://steemhunt.com/@shaphir/steemhq-innovative-services-for-the-steem-ecosystem) but when i clicked the add post button they dont show me the message ```you have already posted 2 products today. Please hunt more tomorrow:)``` when I'm on ```Wallet```

#### How to reproduce
* Before, make sure you have posted 2 products today
* Explore Steemhunt website
* Then, go to ```wallet``` and refresh the page
* Then, click add post button
* You can post the product even after posting 2 products today, no message ```you have already posted 2 products today. Please hunt more tomorrow:)```

* Browser: Google Chore fast & secure version 67.0.3396.87
* Operating system: Android 6.0.1

#### Recording Of The Bug
https://youtu.be/uV2niIFyqdA

**Comment by sydneyitguy** [comment]
This feature is removed now.  Thanks for your reporting :)

**Comment by shaphir** [comment]
Yeah, i know this feature will be deleted because there is a change on the steemhunt that lets the user can post the hunt without any limit, i read the announcement 19 hours ago :)
