### ISSUE TITLE
The website will be stop when i give upvote on the hunt

### ISSUE THREAD

**Issue by shaphir** [Steemhunt/web#242]
I think this only happens to mobile users

#### Actual behavior
When I upvote one of the hunts, the website suddenly stops. For avoid the behavior it, I was forced shoul to close the tab and open the site on a new tab.

Note:
> Sometimes just stop for a few seconds only.

#### How to produce
* Explore the steemhunt website
* Select one post then opened it
* Then give an upvote to the post
* The website will stop

* On android version 6.0.1
* Browser Google Chrome fast & secure version 67.0.3396.87

#### Recording of the bug
https://youtu.be/lClG6zD9sik

**Comment by shaphir** [comment]
Additional. do a comment first on the post before upvote

**Comment by sydneyitguy** [comment]
@shaphir does it happen all the time? or how often (% of chance) it happens?

I haven't seen this issue on my side (mostly using safari & ios devices)

If there's anyone who experienced the same problem, please log your device & os version & browsers here.

**Comment by shaphir** [comment]
@sydneyitguy this behavior happens all the time to me. But that only happens when giving upvote after making a comment.
