### ISSUE TITLE
Comments Displays wrong time just after about 40mins of Publishing

### ISSUE THREAD

**Issue by realrufans** [Steemhunt/web#248]
#### Expected behavior
Comment time on steemHunt just after 40mins ought to correspond with that of steemit.

#### Actual behavior
Comments Displays wrong time just after about 40mins+ of Publishing

#### How to reproduce
* Locate  a  comment that's  about 40mins+ on steemit (must be with a steemhunt tag)
* Note the time displayed on the comment (must be 40mins+)
* click one ```View on Steemhunt.com``` to open same post on steemhunt
* locate that same comment on a hunt then note the time dispaying.

* Browser: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating system: Windows 10

#### Recording Of The Bug
https://www.youtube.com/watch?v=TNdaJF_su8U

**Comment by astrocket** [comment]
It's not a bug since it's correct to display 45mins as 'about' an hour ago.
