### ISSUE TITLE
The hunt that already i upvote doesn't show upvote when i searching for it on the steemhunt

### ISSUE THREAD

**Issue by shaphir** [Steemhunt/web#250]
#### Produce of the bugs
* make a hunt then publish it
* then upvote your hunt
* open a new tab and then search for your hunt on the search button
* your hunt will be show have not yet upvote, except after your open it.

Opening system: Oppi A57 android version 6.0.1
Browser: Google Chrome version 68.0.3440.91

#### Recording of the bug
https://youtu.be/lCPliyTltIM

**Comment by astrocket** [comment]
What do you mean? I don't get it neither from the text nor video.

**Comment by fknmayhem** [comment]
Selfvotes don’t show in HS. 

If not about selfvote, it could be that he means that actual state of score sometimes requires to open a hunt for it to refresh the HS. I think this may have to do with lower speed connectivity.

**Comment by sydneyitguy** [comment]
this is due to synchronization delay on Steem BC
