### ISSUE TITLE
Live (New) Section

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#257]
Got an idea from @monajam's suggestion
and a previous discussion: https://github.com/Steemhunt/api/issues/39

So basically we want to give fair opportunity regardless of posting time because our users are spread around the globe.

Solution would be:

1. Add a "New" section on the top of "Today" section
2. New section default sorting: "Newest"
3. Change back the Today section's default sorting from "Random" to "Hunt Score"

**Comment by sydneyitguy** [comment]
Maybe it's better & safer if we put live section like..
```
3 hours after moderation approved.
```

Because people tend to vote more on approved posts, so timing of moderations can also be affected.

**Comment by fknmayhem** [comment]
Actually, I think it works now. I often review at 11AM KST and it’s normal to see not yet reviewed hunts with HS80 or 110 even. 

There will always be people who follow each other in their Steemit feed and that may affect some scores but generally the top 20 is working.

And newer hunters they seem to quickly grasp when is the time. People adapt rather quickly to how the platform works. And also to how they prefer browsing.

I think that’s ok. Submit early if you have a solid hunt. No need to try to overthink to design “ultimate fairness”, there will always be people who complain. 

But there’s many more who adapted. The statistically negligible cases shouldn’t define the focus nor the design
