### ISSUE TITLE
Replace GIFs with MP4

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#264]
We have many users upload GIFs as a main image, and we don't want to restrict that behavior.
However, too many GIFs, especially large GIF files on the hunt lists make the site very laggy and cause higher usage of CPU and energy on the client side.

One good solution is to convert those GIFs into MP4 files (maybe on uploading time OR background tasks), so we can utilize hardware acceleration as well as saving some network traffic.

Reference:
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/replace-animated-gifs-with-video/

**Comment by astrocket** [comment]
https://github.com/russmatney/lambda-gif-to-mp4

**Comment by sydneyitguy** [comment]
https://github.com/Steemhunt/web/pull/276
