### ISSUE TITLE
Session lost issue before posting (re-login required)

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#294]
When a hunter made content and try to post, the session seems expired many times, which requires users to log-out and re-log in. Because the content is already saved as draft, many hunters are just re-logging in and post it, but we gotta find the reason and fix it soon.

**Comment by sydneyitguy** [comment]
guess it's the issue with Steem RPC Nodes failures.. probably nothing we can do except operating our own RPC nodes and stablize them.

Do you getting those reports more time than the past? @cyh76507707
