### ISSUE TITLE
Profile pic not appeared

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#36]
The profile photo on the top right (nav bar) is not appeared sometimes.
![screenshot 2018-03-05 19 51 53](https://user-images.githubusercontent.com/15100667/36996453-cfe78b40-20ae-11e8-89fe-1ffb4a36319d.png)

**Comment by cyh76507707** [comment]
It was just a temp issue cause of Steemit's network

**Comment by dakeshi** [comment]
I test it several times but I can not get a perfect circle all the times. Is it really steemit network issue?

**Comment by sydneyitguy** [comment]
@cyh76507707 
Yes we get the image from busy.org server, and they have some issue occasionally. We probably need our own image cache at some point.

@dakeshi 
Oh you thought that circle thing is a bug.. Actually it represents your current voting power.
So if the circle is half-filled - means your current voting power is 50%.

**Comment by dakeshi** [comment]
> Actually it represents your current voting power.

If it is true, it is not a good idea, I think. How many people know this is the voting power indicator.
At least, it shows up some pop-up to show voting power with number when hovering on profile image even though I'm not sure this would be good idea on mobile device too.
