### ISSUE TITLE
Voting count is not matched

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#37]
https://steemhunt.com/@aussieninja/ork-hulk-a-warhammer-40-000-inspired-steem-game-on-the-blockchain 
The post above has different voting count appeared on the ranking board and detail view.

![screenshot 2018-03-05 19 49 43](https://user-images.githubusercontent.com/15100667/36996498-e6e64c1e-20ae-11e8-884b-7597b87525aa.png)

**Comment by sydneyitguy** [comment]
It seems like it was a temporary issue?
I can't reproduce the issue.

**Comment by cyh76507707** [comment]
Still the same to me.
![screenshot 2018-03-06 05 23 12](https://user-images.githubusercontent.com/15100667/37015385-b4485626-20fe-11e8-8090-e5dae31a54fa.png)
