### ISSUE TITLE
set up the issue template will help you to check its bug env

### ISSUE THREAD

**Issue by dakeshi** [Steemhunt/web#40]
github issue template can be located in one of the following location:
(https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

- repository's visible root directory
- docs folder, 
- hidden .github directory

I'd like to open PR but I'm not sure which location you prefer to.
So, I just give you some example template.(https://github.com/busyorg/busy/issues/new)

```
<!--
Thanks for opening an issue! To help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 
-->

#### Expected behavior

<!-- What do you think should happen? -->

#### Actual behavior

<!-- What actually happens? -->

#### How to reproduce

<!-- For bugs, provide an URL that demos the problem -->

* Browser: 
* Operating system: 
```

**Comment by sydneyitguy** [comment]
Oh cool. I just added issue template on `.github/issue-template.md`
