### ISSUE TITLE
some text is not legible depending on devices

### ISSUE THREAD

**Issue by dakeshi** [Steemhunt/web#41]
In https://steemhunt.com/about, some text is not legible on some mobile devices.

![steemhunt_-_dig_products__earn_steems](https://user-images.githubusercontent.com/8563047/37006994-81e077ca-211e-11e8-94a3-7d8165fb84a4.png)

testing env: iPhone5S, iPhone7

**Comment by sydneyitguy** [comment]
Thanks heps for your participation 👍
