### ISSUE TITLE
link to busy.org instead of steemit on profile page

### ISSUE THREAD

**Issue by dakeshi** [Steemhunt/web#42]
I think that busy.org is better place to see and write contents than those of steemit.
So, how was change to default profile page to busy.org? 
Or it would be nice to select profile page which a user prefers to on setting page.

![_dakeshi_-_steemhunt](https://user-images.githubusercontent.com/8563047/37008409-2e64bc58-2125-11e8-8c16-1d9601bb58eb.png)

**Comment by sydneyitguy** [comment]
Yes I prefer Busy's UI as well, but Steemit has more users than Busy.org, so I guess it's better to have Steemit link there. 
I guess it would be nice to have an option to choose their profile page for Steemhunt, but that could be a duplicated information with the `website` field (github.com/dakeshi) on Steemit.

@cyh76507707 what do you think?

**Comment by cyh76507707** [comment]
Thanks for your great opinion @dakeshi I also prefer Busy.org's interface. But, so far, people uses Steemit more. Some people who don't know Busy.org may be confused. Thanks again for your opinion!

**Comment by dakeshi** [comment]
You're right. Steemit is the most popular platform according to the last 24h Steem apps leaderboard

1 steemit: 28753 51.48%
2 esteem: 8146 14.59%
3 busy: 5310 9.51%
4 zappl: 3818 6.84%
5 dtube: 2279 4.08%
6 dmania: 1997 3.58%
7 steepshot: 1863 3.34%
8 dlive: 1005 1.80%
9 utopian: 664 1.19%
10 dsound: 640 1.15%
11 steemkr: 374 0.67%
12 steempress: 105 0.19%
13 bescouted: 94 0.17%
14 streemian: 76 0.14%
15 steemauto: 74 0.13%
16 postpromoter: 72 0.13%
17 decentmemes-app: 69 0.12%
18 chainbb: 58 0.10%
19 steemjs: 50 0.09%
20 strimi: 36 0.06%
https://data.chainbb.com/platforms

We can not say that steemhunt users prefer to use steemit.
If you get more referer data(such as google analytics) on steemhunt.com, you can make a better decision with it.

**Comment by sydneyitguy** [comment]
Google Analytics data on day one:

![image](https://user-images.githubusercontent.com/1332279/37066813-6a941abe-21ea-11e8-848f-71399b884d72.png)

Yeah let's keep Steemit for now

**Comment by dakeshi** [comment]
https://staging.busy.org/@cryptoctopus/why-i-might-switch-completely-to-busy-org-steem-referral-links

I agree with what this user points out. steemit front-end is not interested in their UI improvement.
