### ISSUE TITLE
Popular | Newest button

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#57]
Please add nav button on the top right side of the leaderboard to sort products as popular and newest list.

![screenshot 2018-03-09 08 08 23](https://user-images.githubusercontent.com/15100667/37197063-1465b4c6-2371-11e8-817e-7e33080c61b1.png)

**Comment by cyh76507707** [comment]
Sorting options could be based-on three: `Popular / Upvotes / Newest`
>> Sort by upvotes is [suggested by @tehshizno](https://steemit.com/t/@steemhunt/steemhunt-back-end-improvements-13-march#@tehshizno/re-steemhunt-steemhunt-back-end-improvements-13-march-20180312t211511134z)

**Comment by sydneyitguy** [comment]
Resolved with #78
