### ISSUE TITLE
Comment count is not increasing after leaving the comment

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#6]
![screenshot 2018-02-26 15 25 03](https://user-images.githubusercontent.com/15100667/36678726-6a1c7154-1b09-11e8-8a58-ff69b783665a.png)
The above image is when I'm leaving my comment. The comment count on the right side view is not changing after I making it.

![screenshot 2018-02-26 15 25 38](https://user-images.githubusercontent.com/15100667/36678768-853178ea-1b09-11e8-90fe-a91ef888403b.png)
The count is changed when I refresh the page. I guess it may be related to fetching the Steemit data.

**Comment by sydneyitguy** [comment]
@cyh76507707 Can you test it again?
I guess it's fixed now

**Comment by cyh76507707** [comment]
Still the same...
