### ISSUE TITLE
Category (tag) browsing

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#62]
so users can browse top products on each category

**Comment by sydneyitguy** [comment]
maybe sub categories menu

**Comment by cyh76507707** [comment]
Maybe we can make the left side view as a simple category search interface like App Store.
![img_2273](https://user-images.githubusercontent.com/15100667/43009837-a942be4e-8c36-11e8-96d1-61fb6adb1763.PNG)

**Comment by sydneyitguy** [comment]
@cyh76507707 this ticket is closes, and merged with #238
