### ISSUE TITLE
sc2-sdk error handling

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#70]
![](https://cdn.discordapp.com/attachments/423403312931536898/423735057786863616/Screenshot_1.jpg)

This is a STEEM blockchain communication related issue, but we need a better way to handling this.

1. By saving draft - Issue #35
2. Retrying in background

**Comment by cyh76507707** [comment]
Or, simpler/temp way to do, let's change the msg like this:

```There was an error communicating with the STEEM network. Please try again later.```
