### ISSUE TITLE
Different sorting

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#78]
Currently it only sort by payout_value,

but many people suggested that it'd be better if we have other way of sorting like:
sort by
- by voting count
- by number of comments
- by newest

**Comment by Folken8** [comment]
Is this suggestion will change the ranking system?

**Comment by sydneyitguy** [comment]
@Folken8 
I don't think we will change the default sorting method. Default sorting option will be remains the same as now.

This update would be just giving an option for users to sort the product in a different way.
Maybe something like a drop down menu on the top right of the sites.
