### ISSUE TITLE
Blank out bug when posting a specific Youtube link

### ISSUE THREAD

**Issue by cyh76507707** [Steemhunt/web#79]
This is weird bug... when I adding a specific Youtube link on the long desc., the page becomes a white blank like the video I recorded:

![2018-03-19 15_36_33](https://user-images.githubusercontent.com/15100667/37605549-53e6684e-2b8b-11e8-8996-5f6a260dcbe8.gif)

This is the Youtube link from Indigogo - https://www.youtube.com/watch?time_continue=1&v=ccmV158fdSM

This is the error msg on console:
![screenshot 2018-03-19 15 37 27](https://user-images.githubusercontent.com/15100667/37605598-729c727e-2b8b-11e8-9b37-e7564abc499a.png)

**Comment by Folken8** [comment]
AH! I had the same bug sometimes ago!!! I forgot to take a picture. After one hour everything was fine ...
