### ISSUE TITLE
Hunted post on right panel

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#81]
On profile page

**Comment by cyh76507707** [comment]
Maybe display this way:

==============

`Hunted`
12 products, $125.24 hunter's rewards were generated.
1. ~~~~~
2. ~~~~~
3. ~~~~~
...
10. ~~~~~
Show All

`Upvoted`
124 products, $1,356.25 hunter's rewards were generated.
1. ~~~~~
2. ~~~~~
3. ~~~~~
...
10. ~~~~~
Show All

**Comment by sydneyitguy** [comment]
@cyh76507707 
To show "upvoted" section, we may need to change the DB structure and migrate the data. It can be done, but takes a bit of dev time.

Also, showing top 10 results & "Show all" button interface is only a valid approach on our daily ranking page. It's okay to load "all" because the maximum number of daily hunted products may not ever exceed hundreds.  If it becomes thousands, you will not be able to see the sections below anymore because it's too long and it may crash your browser as well.

Therefore, if we create "upvote" section,
1. We need to  change DB structure & migrate all data we have & performance impact in a long term
2. Need a new pagination method like: clicking "Show more" to load 10 more results in the section

Let's split 'upvote section' issue from this one.

**Comment by sydneyitguy** [comment]
Oh and here:
```
Upvoted
124 products, $1,356.25 hunter's rewards were generated.
```
"$1,356.25 hunter's rewards were generated" 

does that mean 
"the total value of my votings"
or
"the total value of posts I voted on"

It's quite confusing.

**Comment by cyh76507707** [comment]
Wow, that's a lot of works... Let's just update 'hunted' section at this time. Yes, what I meant was to show how much rewards generated from what I hunted and upvoted.
