### ISSUE TITLE
Improve Posting Guideline - plagiarism and copyrights 

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#84]
Currently we only have one sentence about it on our posting guidelines
which is
"Also, please make a sentence and description with your own words. If you just simply copy and paste whatever is written on the product’s website or other sites, we won’t upvote your post."

We better improve it in more details to avoid potential troubles in the future (we may need to get an advice from a lawyer or expert)

Suggested by `dakeshi` on our Discord channel

* Also putting posting guidelines as a placeholder on Description would be better for visilbiilty (maybe it's too long?)

**Comment by dakeshi** [comment]
I suggest to similar UI like GitHub issue.
![_2018-03-23_ _11_49_47](https://user-images.githubusercontent.com/8563047/37811498-f909b4d8-2e9d-11e8-8453-65be7f1fecf3.png)

**Comment by cyh76507707** [comment]
Hello, @dakeshi 

Thanks so much for your great opinion. We are going to revise the current posting guidelines more clear way like below, and will add a checkbox over the posting button saying, `I have read the posting guidelines` when a user makes his or her first post.

===========================
<br>
<br>

# Posting Guidelines

Steemhunt is a ranking community run by early-adopters who hunt "effortlessly cool products." Please follow these guidelines when making a post. If your post fails to follow the guidelines, it may be excluded from the ranking.

<hr>

## 1. Post a "Product," not a "Business."
A business is larger and more vague than a product. For example, you may post a new Samsung Galaxy S9 phone - this is a product. You can’t post "Samsung" itself - this is a business. Also, you can’t post a local product. Steemhunt is a global community, so you should bring something that everyone can enjoy.

## 2. Types of Products to Post
Steemhunt generally covers unique IT or hardware products, including:
* Web services
* Mobile apps
* Games
* API, IT solutions, bots, open sources or other types of software
* Tech gadgets
* Unique items

## 3. Language - English Only
Steemhunt runs a single ranking board globally, so please post and comment in English.

## 4. Product Link
All posts must have a valid website. You can only provide an official website of the product, app download link, or e-commerce site where users can make purchases. The following examples WILL NOT be accepted:
* Newspaper articles
* Listicles (like '00 cool inventions …')
* Blog posts (unless it’s a launching post.)
* Social media posts such as Facebook, Twitter, Youtube, or Instagram

## 5. Plagiarism and Copyright
Write a sentence and description with your own words. Do not copy and paste from the product’s website or other sites. You can however quote some content from a site, but you must use quotes and cite the source properly.

## 6. Do Not Use Upvoting Bot
Using an upvoting bot service may disrupt our daily ranking. This is a product community where "people" actually see the product you’ve hunted, and upvote the products they think are cool. 

## 7. Post "New" Products
Steemhunt is about cool "new" products. Please make sure that your hunt is about something that’s recently introduced. If the product is not new, there must be strong reason to post. For example, the product must be substantially updated or upgraded in a way that has a positive effect on users. Or, it must be a product that not many people have observed and may be interesting to discover.

<hr>

These posting guidelines are being continuously developed by our community. Feel free to suggest any opinions on how to make Steemhunt a cooler ranking community. You can join our [Discord Chat](https://discord.gg/mWXpgks) and make any suggestions.

**Comment by dakeshi** [comment]
Thanks for your works. I got a two suggestions about guideline.

> will add a checkbox over the posting button saying, I have read the posting guidelines when a user makes his or her first post.

Personally, I prefer to use it as reference instead of just showing it up during the first posting.

> Post "New" Products

What is the new? It looks unclear. How was setting up periods such as longer than 60 days after it is released

Would you make this guideline as a PR to take a review when you have completed an initial guideline?

**Comment by sydneyitguy** [comment]
@dakeshi 
1. 
We're thinking of showing the checkbox on the first posting & reference link popup on the top right corner of the posting page (as it is now) all the time.

![image](https://user-images.githubusercontent.com/1332279/37950515-bf922634-31d3-11e8-930a-5424b93d3905.png)

2.
Yes, the term "New" is ambiguous.
In my opinion, however, it can't be strictly defined period based on the release date because a company (or hunter) sometimes want to feature a product on Steemhunt after a while, once the product has been mature enough to be advertised, like we would post Steemhunt on Producthunt once it has enough users to show off :p 

Also we love to people post a major upgrade of existing products (e.g. [Airbnb Experience](https://www.airbnb.com/host/experiences/) and [Airbnb Concerts](https://www.airbnb.com/s/experiences?refinement_paths%5B%5D=%2Fexperiences%2FConcept%2FRefinement%2FConcerts&redirectSource=concerts) feature updates)

**Comment by sydneyitguy** [comment]
I just added this on the repo
https://github.com/Steemhunt/web/blob/master/POSTING_GUIDELINES.md

so we can use this link as a reference and ppl can contribute changing it via pull requests.

**Comment by cyh76507707** [comment]
Make PG (Posting Guidelines) structures like as below:

[General Rules]
1.
2.
...

[Rules for Section 1. App/Web/...]
1.
2
...

[Rules for Section 2. Games]
1.
2.
...

[Moderations]

[Appeal Process]

[Blacklist Actions]
