### ISSUE TITLE
Flag feature

### ISSUE THREAD

**Issue by sydneyitguy** [Steemhunt/web#95]

**Comment by Chuuuckie** [comment]
Disable Flag Feature. We don't need this.

**Comment by Folken8** [comment]
I disagree. Flagging abusers can be a solution after X warnings.

**Comment by Chuuuckie** [comment]
Flagging only when needed too. It is not necessary.

But some users wont flag, steemhunt needs another account for flags or invite someone from flag communities.

**Comment by Folken8** [comment]
Well there is no description on this issue. Wait & see
